language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libxmlsec1-dev
gemfile:
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_5.1.gemfile
  - gemfiles/activerecord_5.2.gemfile
  - gemfiles/activerecord_6.0.gemfile
script: bundle exec rake spec
